source "http://rubygems.org"

gem 'jekyll', '~>1.4.0'
gem '<%= markdownEngine %>'<% if (cssPreprocessor === 'sass') { %>
gem 'sass', '>=3.2'<% } %><%  if (cssPreprocessor === 'compass') { %>
gem 'compass', '>=0.12'<%     } %>
