source "http://rubygems.org"

gem 'jekyll'
gem 'redcarpet'
gem 'classifier-reborn'

# jekyll plugins
gem 'jekyll-archives'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'jekyll-feed'
gem 'jekyll-gist'

# octopress
gem 'octopress', '~> 3.0'
